position = "top"
height = 31
margin = { top = 4, bottom = 4 }
layer = "top"

# ===================
#    BARRA SUPERIOR
# ===================

[[bars]]
name = "main"
position = "top"
height = 31

# -------------------
#    SECCIÓN IZQUIERDA
# -------------------
[[bars.left]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-left"

[[bars.left]]
type = "custom"
command = "echo 'APPS'"
interval = 0
on_click = "yofi"
id = "appmenu"

[[bars.left]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-left-secondary"

[[bars.left]]
type = "workspaces"
active_only = false
all_outputs = true
persistent = 5
icons = { "1" = "", "2" = "", "3" = "", "4" = "", "5" = "" }
empty_icon = ""
default_icon = ""

[[bars.left]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-left-transparent"

[[bars.left]]
type = "window_title"
max_length = 1000
format = "  {} "

# -------------------
#  SECCIÓN CENTRO
# -------------------
[[bars.center]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-right-secondary-transparent"

[[bars.center]]
type = "custom"
command = "echo ''"
interval = 0
id = "arch"

[[bars.center]]
type = "clock"
format = "  %H:%M"
format_alt = "  %H:%M   %Y, %d %B, %A"

[[bars.center]]
type = "custom"
command = "echo ''"
interval = 0
id = "dot-wallpaper"

[[bars.center]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-left-secondary-transparent"

# -------------------
#  SECCIÓN DERECHA
# -------------------
[[bars.right]]
type = "network"
format_wifi = "{icon}  {up}  {down}"
format_ethernet = "󰌘  {up}  {down}"
format_disconnected = "󰌙"
id = "network"

[[bars.right]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-right-transparent"

[[bars.right]]
type = "custom"
command = "~/.config/hypr/scripts/WaybarCava.sh"
interval = 0
id = "cava"

[[bars.right]]
type = "custom"
command = "echo ''"
interval = 0
id = "upper-right-secondary"

# --- STATUS GROUP ---
[[bars.right]]
type = "pulseaudio"

[[bars.right]]
type = "pulseaudio"
source = true
id = "microphone"

[[bars.right]]
type = "custom"
command = "~/.config/hypr/scripts/Bluetooth.sh status"
return_format = "json"
interval = 10
id = "bluetooth"

# --- SYSTEM GROUP ---
[[bars.right]]
type = "backlight"

[[bars.right]]
type = "battery"

[[bars.right]]
type = "custom"
command = "echo ''"
on_click = "~/.config/hypr/scripts/Wlogout.sh"
id = "power"
