format = """
[](#2e3436)\
[  ](bg:#303030 fg:#c4a000)\
[](bg:#303030 fg:#a3aed2)\
$directory\
$git_branch\
$git_status\
[](fg:#303030 bg:#3e4042)\
$c\
$php\
$java\
$rust\
$nodejs\
$golang\
$kotlin\
$python\
$haskell\
$time\
[](fg:#3e4042)\
\n$character"""


[directory]
style = "fg:#3387c8 bg:#303030"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = " "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Images" = " "
"Desktop" = " "
"Videos" = " "
"Projects" = " "
"fonts" = " "
".config" = " "
"root" = " "
"repos" = " "
"settings" = " "
"Private" = " "

[git_branch]
symbol = ""
style = "bg:#3e4042"
format = '[[ $symbol $branch ](fg:#3387c8 bg:#303030)]($style)'

[git_status]
style = "bg:#3e4042"
format = '[[($all_status$ahead_behind )](fg:#3387c8 bg:#303030)]($style)'


[c]
symbol = " "
style = "bg:3e4042"
format = '[[ $symbol( $version) ](fg:#3387c8 bg:3e4042)]($style)'

[nodejs]
symbol = ""
style = "bg:#3e4042"
format = '[[ $symbol ($version) ](fg:#3387c8 bg:#3e4042)]($style)'

[rust]
symbol = ""
style = "bg:#3e4042"
format = '[[ $symbol ($version) ](fg:#3387c8 bg:#3e4042)]($style)'

[golang]
symbol = ""
style = "bg:#3e4042"
format = '[[ $symbol ($version) ](fg:#3387c8 bg:#3e4042)]($style)'

[php]
symbol = ""
style = "bg:#3e4042"
format = '[[ $symbol ($version) ](fg:#3387c8 bg:#3e4042)]($style)'

[java]
symbol = " "
style = "bg:3e4042"
format = '[[ $symbol( $version) ](fg:#3387c8 bg:#3e4042)]($style)'

[kotlin]
symbol = ""
style = "bg:3e4042"
format = '[[ $symbol( $version) ](fg:#3387c8 bg:#3e4042)]($style)'

[haskell]
symbol = ""
style = "bg:3e4042"
format = '[[ $symbol( $version) ](fg:#3387c8 bg:#3e4042)]($style)'

[python]
symbol = ""
style = "bg:3e4042"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:#3387c8 bg:#3e4042)]($style)'

[time]
disabled = false
time_format = "%R"                                       # Hour:Minute Format
style = "bg:#2e3436"
format = '[[   $time ](fg:#b0b0b0 bg:#3e4042)]($style)'
